<?php
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");
?>
				<? $APPLICATION->IncludeComponent(
                    "bitrix:sale.basket.basket", 
                    "addBasket", 
                    array(
                        "IDS" => $_REQUEST['ids'],
                        "COLUMNS_LIST" => array(
                            0 => "NAME",
                            1 => "DISCOUNT",
                            2 => "DELETE",
                            3 => "DELAY",
                            4 => "TYPE",
                            5 => "PRICE",
                            6 => "QUANTITY",
                            7 => "SUM",
                            8 => "PROPERTY_CML2_ARTICLE",
                            9 => "PROPERTY_YEAR",
                        ),
                        "PATH_TO_ORDER" => "/personal/order/make/",
                        "HIDE_COUPON" => "N",
                        "PRICE_VAT_SHOW_VALUE" => "N",
                        "COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
                        "USE_PREPAYMENT" => "N",
                        "QUANTITY_FLOAT" => "N",
                        "SET_TITLE" => "Y",
                        "ACTION_VARIABLE" => "action",
                        "OFFERS_PROPS" => array(
                            0 => "COLOR_DIRECTORY",
                            1 => "COLOR2_DIRECTORY",
                            2 => "STORAGE",
                        ),
                        "PROP_ARTICLE" => "CML2_ARTICLE",
                        "PROP_SKU_ARTICLE" => "CML2_ARTICLE",
                        "AJAX_MODE" => "Y",
                        "COMPONENT_TEMPLATE" => "gopro",
                        "AJAX_OPTION_JUMP" => "N",
                        "AJAX_OPTION_STYLE" => "Y",
                        "AJAX_OPTION_HISTORY" => "N",
                        "AJAX_OPTION_ADDITIONAL" => "undefined",
                        "CORRECT_RATIO" => "N",
                        "AUTO_CALCULATION" => "Y",
                        "ACCESSORIES_IBLOCK" => "-",
                        "PROP_ACCESSORIES" => "-",
                        "USE_GIFTS" => "Y",
                        "GIFTS_PLACE" => "BOTTOM",
                        "GIFTS_BLOCK_TITLE" => "Выберите один из подарков",
                        "GIFTS_HIDE_BLOCK_TITLE" => "N",
                        "GIFTS_TEXT_LABEL_GIFT" => "Подарок",
                        "GIFTS_PRODUCT_QUANTITY_VARIABLE" => "undefined",
                        "GIFTS_PRODUCT_PROPS_VARIABLE" => "prop",
                        "GIFTS_SHOW_OLD_PRICE" => "N",
                        "GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
                        "GIFTS_SHOW_NAME" => "Y",
                        "GIFTS_SHOW_IMAGE" => "Y",
                        "GIFTS_MESS_BTN_BUY" => "Выбрать",
                        "GIFTS_MESS_BTN_DETAIL" => "Подробнее",
                        "GIFTS_PAGE_ELEMENT_COUNT" => "4",
                        "GIFTS_CONVERT_CURRENCY" => "N",
                        "GIFTS_HIDE_NOT_AVAILABLE" => "N",
                        "CATALOG_LINK" => "/catalog/"
                    ),
                    false
                );?>
<?php
/*

$APPLICATION->IncludeComponent(
	"bitrix:catalog.section",
	"addBasket",
	array (
		'IBLOCK_TYPE' => 'catalog',
		'IBLOCK_ID' => 2,
		'ELEMENT_SORT_FIELD' => 'SORT',
		'ELEMENT_SORT_ORDER' => 'ASC',
		'ELEMENT_SORT_FIELD2' => 'shows',
		'ELEMENT_SORT_ORDER2' => 'asc',
		'PROPERTY_CODE' => 
		array (
		1 => 'CML2_ARTICLE',
		2 => 'BRAND',
		3 => 'OS',
		4 => 'WEIGHT',
		5 => 'HEIGHT',
		6 => 'TICKNESS',
		7 => 'WIDTH',
		8 => 'DIAGONAL',
		9 => 'SOLUTION',
		10 => 'INTERNET_ACCESS',
		11 => 'INTERFACES',
		12 => 'NAVI',
		13 => 'CARD',
		14 => 'VIDEO',
		15 => 'ACCESSORIES',
		16 => 'BUY_WITH_THIS',
		),
		'META_KEYWORDS' => '-',
		'META_DESCRIPTION' => '-',
		'BROWSER_TITLE' => '-',
		'INCLUDE_SUBSECTIONS' => 'Y',
		'BASKET_URL' => '/personal/cart/',
		'ACTION_VARIABLE' => 'action',
		'PRODUCT_ID_VARIABLE' => 'id',
		'SECTION_ID_VARIABLE' => 'SECTION_ID',
		'PRODUCT_QUANTITY_VARIABLE' => 'quantity',
		'PRODUCT_PROPS_VARIABLE' => 'prop',
		'FILTER_NAME' => 'arrFilter',
		'CACHE_TYPE' => 'A',
		'CACHE_TIME' => '36000000',
		'CACHE_FILTER' => false,
		'CACHE_GROUPS' => 'Y',
		'SET_TITLE' => true,
		'SET_STATUS_404' => 'Y',
		'DISPLAY_COMPARE' => true,
		'PAGE_ELEMENT_COUNT' => 30,
		'LINE_ELEMENT_COUNT' => 0,
		'PRICE_CODE' => 
		array (
		0 => 'BASE',
		),
		'USE_PRICE_COUNT' => false,
		'SHOW_PRICE_COUNT' => 1,
		'PRICE_VAT_INCLUDE' => true,
		'USE_PRODUCT_QUANTITY' => true,
		'PRODUCT_PROPERTIES' => 
		array (
		),
		'DISPLAY_TOP_PAGER' => false,
		'DISPLAY_BOTTOM_PAGER' => true,
		'PAGER_TITLE' => 'Товары',
		'PAGER_SHOW_ALWAYS' => true,
		'PAGER_TEMPLATE' => '.default',
		'PAGER_DESC_NUMBERING' => false,
		'PAGER_DESC_NUMBERING_CACHE_TIME' => 36000,
		'PAGER_SHOW_ALL' => false,
		'OFFERS_CART_PROPERTIES' => 
		array (
		),
		'OFFERS_FIELD_CODE' => 
		array (
		),
		'OFFERS_PROPERTY_CODE' => 
		array (
		0 => 'KATEGORY_MATERIALA',
		1 => 'KRASHENIE',
		2 => 'NALICHIE_MEHANIZMA',
		),
		'OFFERS_SORT_FIELD' => 'CATALOG_PRICE_1',
		'OFFERS_SORT_ORDER' => 'asc',
		'OFFERS_SORT_FIELD2' => 'shows',
		'OFFERS_SORT_ORDER2' => 'asc',
		'OFFERS_LIMIT' => 0,
		'ADD_SECTIONS_CHAIN' => true,
		'SECTION_ID' => 0,
		'SECTION_CODE' => '',
		'SECTION_URL' => '/#SECTION_CODE_PATH#/',
		'DETAIL_URL' => '/#SECTION_CODE_PATH#/#ELEMENT_CODE#.html',
		'CONVERT_CURRENCY' => 'N',
		'CURRENCY_ID' => '',
		'HIDE_NOT_AVAILABLE' => 'Y',
		'LABEL_PROP' => 
		array (
		),
		'ADD_PICT_PROP' => '-',
		'PRODUCT_DISPLAY_MODE' => 'N',
		'OFFER_ADD_PICT_PROP' => '-',
		'OFFER_TREE_PROPS' => 
		array (
		),
		'PRODUCT_SUBSCRIPTION' => 'Y',
		'SHOW_DISCOUNT_PERCENT' => 'N',
		'SHOW_OLD_PRICE' => 'N',
		'MESS_BTN_BUY' => 'Купить',
		'MESS_BTN_ADD_TO_BASKET' => 'В корзину',
		'MESS_BTN_SUBSCRIBE' => 'Подписаться',
		'MESS_BTN_DETAIL' => 'Подробнее',
		'MESS_NOT_AVAILABLE' => 'Нет в наличии',
		'VIEW' => NULL,
		'AJAX_MODE' => 'Y',
		'AJAX_OPTION_JUMP' => 'N',
		'AJAX_OPTION_STYLE' => 'Y',
		'AJAX_OPTION_HISTORY' => 'N',
		'AJAX_ID' => '02af0f9613c501ff8aa4b4e6990f294b',
		'CURRENT_BASE_PAGE' => '',
		'PARENT_NAME' => 'bitrix:catalog',
		'PARENT_TEMPLATE_NAME' => 'visual',
		'PARENT_TEMPLATE_PAGE' => 'section',
		'SET_BROWSER_TITLE' => 'Y',
		'SET_META_KEYWORDS' => 'Y',
		'SET_META_DESCRIPTION' => 'Y',
		'SET_LAST_MODIFIED' => false,
		'COMPARE_PATH' => '?action=COMPARE',
		'COMPARE_NAME' => 'CATALOG_COMPARE_LIST',
		'FILL_ITEM_ALL_PRICES' => false,
		'ADD_PROPERTIES_TO_BASKET' => 'Y',
		'PARTIAL_PRODUCT_PROPERTIES' => 'N',
		'SHOW_FROM_SECTION' => 'N',
		'FILTER_IDS' => 
		array (
		),
		'ELEMENT_COUNT' => 0,
		'HIDE_NOT_AVAILABLE_OFFERS' => 'N',
		'CUSTOM_FILTER' => 
		array (
		),
		'LAZY_LOAD' => 'N',
		'LOAD_ON_SCROLL' => 'N',
		'MESS_BTN_LAZY_LOAD' => '',
		'SHOW_ALL_WO_SECTION' => false,
		'USE_MAIN_ELEMENT_SECTION' => false,
		'BACKGROUND_IMAGE' => '',
		'CUSTOM_CURRENT_PAGE' => '',
		'COMPATIBLE_MODE' => 'Y',
		'DISABLE_INIT_JS_IN_COMPONENT' => 'N',
	)
);*/